language: go
go: 1.15

services:
  - mongodb # 2.4.12

install:
  - go version
  - export PATH=$PATH:$HOME/gopath/bin
  # - go get -v github.com/pearlnote/pearlnote/app
  - go get -u github.com/revel/cmd/revel
  # - ls $GOPATH/src/github.com/revel/
  # - go get github.com/revel/moudle/revel
  # - go install github.com/revel/cmd/revel
  - revel version
  - pwd
  - ls

script:
  - wget https://github.com/pearlnote/pearlnote/archive/refs/heads/master.zip
  - unzip master.zip
  - mv pearlnote-master pearlnote
  - cd pearlnote

  - mongo --version
  - mongorestore -h localhost -d pearlnote --dir ./mongodb_backup/pearlnote_install_data/

  - cd ./sh
  # - cd $GOPATH/src/github.com/pearlnote/pearlnote/sh
  - sh run.sh &

  # gen tmp/main.go, routes/routes.go
  #- go run app/cmd/main.go
  # build
  #- go build -o pearlnote github.com/pearlnote/pearlnote/app/tmp
  # run with port 9000
  #- ./pearlnote -importPath=github.com/pearlnote/pearlnote -runMode=dev -port=9000 &

  - sleep 10s;
  # test
  - curl http://localhost:9000
  - curl http://localhost:9000/blog
  - curl http://localhost:9000/login
  - curl http://localhost:9000/demo

  # - revel build github.com/pearlnote/pearlnote tmp
  # OK
