version: '3.3'
services:

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ~/mongo_data:/data

  pearlnote:
    build: .
    image: pearlnote:1.0.0
    container_name: pearlnote
    restart: always
    depends_on:
      - mongodb
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ~/pearlnote/conf/app.conf:/opt/pearlnote/conf/app.conf
