version: '3.3'
services:

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: pearlnote
      POSTGRES_PASSWORD: pearlnote
      POSTGRES_DB: pearlnote
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/001-pearlnote-schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/002-pearlnote-seed.sql:ro

  pearlnote:
    build: .
    image: pearlnote:1.0.0
    container_name: pearlnote
    restart: always
    depends_on:
      - postgres
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ~/pearlnote/conf/app.conf:/opt/pearlnote/conf/app.conf
