-- Pearlnote PostgreSQL schema. IDs use MongoDB-compatible ObjectId hex strings.
BEGIN;

CREATE TABLE IF NOT EXISTS users (
 id CHAR(24) PRIMARY KEY, email TEXT NOT NULL, verified BOOLEAN NOT NULL DEFAULT FALSE,
 username TEXT NOT NULL, username_raw TEXT NOT NULL DEFAULT '', pwd TEXT NOT NULL DEFAULT '',
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, logo TEXT NOT NULL DEFAULT '', theme TEXT NOT NULL DEFAULT '',
 notebook_width INTEGER NOT NULL DEFAULT 0, note_list_width INTEGER NOT NULL DEFAULT 0,
 md_editor_width INTEGER NOT NULL DEFAULT 0, left_is_min BOOLEAN NOT NULL DEFAULT FALSE,
 third_user_id TEXT NOT NULL DEFAULT '', third_username TEXT NOT NULL DEFAULT '', third_type INTEGER NOT NULL DEFAULT 0,
 image_num INTEGER NOT NULL DEFAULT 0, image_size BIGINT NOT NULL DEFAULT 0,
 attach_num INTEGER NOT NULL DEFAULT 0, attach_size BIGINT NOT NULL DEFAULT 0,
 from_user_id CHAR(24), account_type TEXT NOT NULL DEFAULT '', account_start_time TIMESTAMPTZ, account_end_time TIMESTAMPTZ,
 max_image_nums INTEGER NOT NULL DEFAULT 0, max_image_size BIGINT NOT NULL DEFAULT 0,
 max_attach_num INTEGER NOT NULL DEFAULT 0, max_attach_size BIGINT NOT NULL DEFAULT 0,
 max_per_attach_size BIGINT NOT NULL DEFAULT 0, usn INTEGER NOT NULL DEFAULT 0, full_sync_before TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS notebooks (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, parent_notebook_id CHAR(24), seq INTEGER NOT NULL DEFAULT 0,
 title TEXT NOT NULL DEFAULT '', url_title TEXT NOT NULL DEFAULT '', number_notes INTEGER NOT NULL DEFAULT 0,
 is_trash BOOLEAN NOT NULL DEFAULT FALSE, is_blog BOOLEAN NOT NULL DEFAULT FALSE,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 usn INTEGER NOT NULL DEFAULT 0, is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS notes (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, created_user_id CHAR(24), notebook_id CHAR(24) NOT NULL,
 title TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', src TEXT NOT NULL DEFAULT '', img_src TEXT NOT NULL DEFAULT '',
 tags TEXT[] NOT NULL DEFAULT '{}', is_trash BOOLEAN NOT NULL DEFAULT FALSE, is_blog BOOLEAN NOT NULL DEFAULT FALSE,
 url_title TEXT NOT NULL DEFAULT '', is_recommend BOOLEAN NOT NULL DEFAULT FALSE, is_top BOOLEAN NOT NULL DEFAULT FALSE,
 has_self_defined BOOLEAN NOT NULL DEFAULT FALSE, read_num INTEGER NOT NULL DEFAULT 0, like_num INTEGER NOT NULL DEFAULT 0,
 comment_num INTEGER NOT NULL DEFAULT 0, is_markdown BOOLEAN NOT NULL DEFAULT FALSE, attach_num INTEGER NOT NULL DEFAULT 0,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 recommend_time TIMESTAMPTZ, public_time TIMESTAMPTZ, updated_user_id CHAR(24),
 usn INTEGER NOT NULL DEFAULT 0, is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS note_contents (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, is_blog BOOLEAN NOT NULL DEFAULT FALSE,
 content TEXT NOT NULL DEFAULT '', abstract TEXT NOT NULL DEFAULT '',
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_user_id CHAR(24)
);
CREATE TABLE IF NOT EXISTS note_content_histories (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, histories JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS share_notebooks (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, to_user_id CHAR(24), to_group_id CHAR(24), to_group JSONB,
 notebook_id CHAR(24) NOT NULL, seq INTEGER NOT NULL DEFAULT 0, perm INTEGER NOT NULL DEFAULT 0,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS share_notes (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, to_user_id CHAR(24), to_group_id CHAR(24), to_group JSONB,
 note_id CHAR(24) NOT NULL, perm INTEGER NOT NULL DEFAULT 0, created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS has_share_notes (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, to_user_id CHAR(24) NOT NULL, seq INTEGER NOT NULL DEFAULT 0,
 UNIQUE (user_id, to_user_id)
);

CREATE TABLE IF NOT EXISTS groups (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, title TEXT NOT NULL DEFAULT '', user_count INTEGER NOT NULL DEFAULT 0,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, users JSONB
);
CREATE TABLE IF NOT EXISTS group_users (
 id CHAR(24) PRIMARY KEY, group_id CHAR(24) NOT NULL, user_id CHAR(24) NOT NULL,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tags (id CHAR(24) PRIMARY KEY, tags TEXT[] NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS note_tags (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, tag TEXT NOT NULL DEFAULT '', usn INTEGER NOT NULL DEFAULT 0,
 count INTEGER NOT NULL DEFAULT 0, created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS tag_count (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, tag TEXT NOT NULL DEFAULT '',
 is_blog BOOLEAN NOT NULL DEFAULT FALSE, count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS blogs (
 id CHAR(24) PRIMARY KEY, read_num INTEGER NOT NULL DEFAULT 0,
 like_num INTEGER NOT NULL DEFAULT 0, comment_num INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS user_blogs (
 id CHAR(24) PRIMARY KEY, logo TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', sub_title TEXT NOT NULL DEFAULT '',
 about_me TEXT NOT NULL DEFAULT '', can_comment BOOLEAN NOT NULL DEFAULT FALSE, comment_type TEXT NOT NULL DEFAULT '',
 disqus_id TEXT NOT NULL DEFAULT '', style TEXT NOT NULL DEFAULT '', css TEXT NOT NULL DEFAULT '', theme_id CHAR(24),
 theme_path TEXT NOT NULL DEFAULT '', cate_ids TEXT[] NOT NULL DEFAULT '{}', singles JSONB NOT NULL DEFAULT '[]'::jsonb,
 per_page_size INTEGER NOT NULL DEFAULT 0, sort_field TEXT NOT NULL DEFAULT '', is_asc BOOLEAN NOT NULL DEFAULT FALSE,
 sub_domain TEXT NOT NULL DEFAULT '', domain TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS blog_singles (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, title TEXT NOT NULL DEFAULT '', url_title TEXT NOT NULL DEFAULT '',
 content TEXT NOT NULL DEFAULT '', updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS blog_likes (
 id CHAR(24) PRIMARY KEY, note_id CHAR(24) NOT NULL, user_id CHAR(24) NOT NULL,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS blog_comments (
 id CHAR(24) PRIMARY KEY, note_id CHAR(24) NOT NULL, user_id CHAR(24) NOT NULL, content TEXT NOT NULL DEFAULT '',
 to_comment_id CHAR(24), to_user_id CHAR(24), like_num INTEGER NOT NULL DEFAULT 0,
 like_user_ids TEXT[] NOT NULL DEFAULT '{}', created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS reports (
 id CHAR(24) PRIMARY KEY, note_id CHAR(24) NOT NULL, user_id CHAR(24) NOT NULL,
 reason TEXT NOT NULL DEFAULT '', comment_id CHAR(24), created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS albums (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, name TEXT NOT NULL DEFAULT '', type INTEGER NOT NULL DEFAULT 0,
 seq INTEGER NOT NULL DEFAULT 0, created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS files (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, album_id CHAR(24), name TEXT NOT NULL DEFAULT '',
 title TEXT NOT NULL DEFAULT '', size BIGINT NOT NULL DEFAULT 0, type TEXT NOT NULL DEFAULT '', path TEXT NOT NULL DEFAULT '',
 is_default_album BOOLEAN NOT NULL DEFAULT FALSE, created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 from_file_id CHAR(24)
);
CREATE TABLE IF NOT EXISTS attachs (
 id CHAR(24) PRIMARY KEY, note_id CHAR(24) NOT NULL, upload_user_id CHAR(24) NOT NULL,
 name TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', size BIGINT NOT NULL DEFAULT 0,
 type TEXT NOT NULL DEFAULT '', path TEXT NOT NULL DEFAULT '', created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS note_images (id CHAR(24) PRIMARY KEY, note_id CHAR(24) NOT NULL, image_id CHAR(24) NOT NULL);

CREATE TABLE IF NOT EXISTS configs (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24), key TEXT NOT NULL DEFAULT '', value_str TEXT NOT NULL DEFAULT '',
 value_arr TEXT[] NOT NULL DEFAULT '{}', value_map JSONB NOT NULL DEFAULT '{}'::jsonb,
 value_arr_map JSONB NOT NULL DEFAULT '[]'::jsonb, is_arr BOOLEAN NOT NULL DEFAULT FALSE,
 is_map BOOLEAN NOT NULL DEFAULT FALSE, is_arr_map BOOLEAN NOT NULL DEFAULT FALSE,
 updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 id CHAR(24) PRIMARY KEY, session_id TEXT NOT NULL, login_times INTEGER NOT NULL DEFAULT 0,
 captcha TEXT NOT NULL DEFAULT '', user_id TEXT NOT NULL DEFAULT '',
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tokens (
 id CHAR(24) PRIMARY KEY, email TEXT NOT NULL DEFAULT '', token TEXT NOT NULL DEFAULT '', type INTEGER NOT NULL DEFAULT 0,
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS email_logs (
 id CHAR(24) PRIMARY KEY, email TEXT NOT NULL DEFAULT '', subject TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '',
 msg TEXT NOT NULL DEFAULT '', ok BOOLEAN NOT NULL DEFAULT FALSE, created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS suggestions (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24), addr TEXT NOT NULL DEFAULT '', suggestion TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS themes (
 id CHAR(24) PRIMARY KEY, user_id CHAR(24) NOT NULL, name TEXT NOT NULL DEFAULT '', version TEXT NOT NULL DEFAULT '',
 author TEXT NOT NULL DEFAULT '', author_url TEXT NOT NULL DEFAULT '', path TEXT NOT NULL DEFAULT '',
 info JSONB NOT NULL DEFAULT '{}'::jsonb, is_active BOOLEAN NOT NULL DEFAULT FALSE,
 is_default BOOLEAN NOT NULL DEFAULT FALSE, style TEXT NOT NULL DEFAULT '',
 created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notes_user_notebook ON notes(user_id, notebook_id);
CREATE INDEX IF NOT EXISTS idx_notes_sync ON notes(user_id, usn);
CREATE INDEX IF NOT EXISTS idx_notes_tags ON notes USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_notebooks_user ON notebooks(user_id);
CREATE INDEX IF NOT EXISTS idx_note_contents_user ON note_contents(user_id);
CREATE INDEX IF NOT EXISTS idx_share_notes_target ON share_notes(to_user_id, note_id);
CREATE INDEX IF NOT EXISTS idx_share_notebooks_target ON share_notebooks(to_user_id, notebook_id);
CREATE INDEX IF NOT EXISTS idx_files_user_album ON files(user_id, album_id);
CREATE INDEX IF NOT EXISTS idx_blog_comments_note ON blog_comments(note_id, created_time);

COMMIT;
